language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: releases
  api_key: "6c94490d660457c118b108e97319d5db4e44154f"
  file: "/home/travis/build/emptySpecter2/otus_homeworl_1/helloworld-0.0.1-Linux.deb"
  skip_cleanup: true
  on:
    tags: true